apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rtms-hpa
  namespace: rtms-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rtms-deployment
  minReplicas: 3
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: rtms_custom_metric
        target:
          type: AverageValue
          averageValue: "5"