name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [java, python, go, scala]
        java-version: [11]
        python-version: [3.8]
        go-version: [1.17]
        scala-version: [2.13.6]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        if: matrix.language == 'java'
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Go
        if: matrix.language == 'go'
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up Scala
        if: matrix.language == 'scala'
        run: |
          sudo apt-get update
          sudo apt-get install -y scala

      - name: Install dependencies (Python)
        if: matrix.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies (Go)
        if: matrix.language == 'go'
        run: |
          go mod download

      - name: Install dependencies (Scala)
        if: matrix.language == 'scala'
        run: |
          sbt compile

      - name: Build (Java)
        if: matrix.language == 'java'
        run: |
          ./gradlew build

      - name: Run tests (Python)
        if: matrix.language == 'python'
        run: |
          python -m unittest discover -s tests

      - name: Run tests (Go)
        if: matrix.language == 'go'
        run: |
          go test ./...

      - name: Run tests (Scala)
        if: matrix.language == 'scala'
        run: |
          sbt test

      - name: Run tests (Java)
        if: matrix.language == 'java'
        run: |
          ./gradlew test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Python
        run: |
          pip install flake8
          flake8 .

      - name: Lint Go
        run: |
          go fmt ./...

      - name: Lint Scala
        run: |
          sbt scalastyle

      - name: Lint Java
        run: |
          ./gradlew checkstyleMain checkstyleTest

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t messaging-system:latest .

      - name: Run Docker container
        run: |
          docker-compose up -d